### ISSUE TITLE
An alternative way of managing effects in `capability`

### ISSUE THREAD

**Issue by re-xyr** [tweag/capability#101]
(I'm not sure if this is the right place for suggesting this; if it isn't appropriate feel free to close this)

In `capability` (and `mtl`), the pattern of restricting what a computation can do is by imposing constraints on a polymorphic monad type:

```haskell
app :: HasState MyState m => m ()
```

[As Alexis King pointed out](https://www.youtube.com/watch?v=0jI-AlWEwYI), this approach has inevitable performance cost. On the other hand, using a *concrete* monad admits more optimizations, but it automatically allows you to do all operations implemented for that monad, so restriction is not possible:

```haskell
newtype App a = App { runApp :: Reader Env IO a }
  deriving (Functor, Applicative, Monad, MonadIO)
  deriving (HasSource "r" SomeType) via ...
  deriving (HasSink "s" SomeOtherType) via ...
app :: HasSink "s" SomeOtherType App => App ()
-- The constraint is redundant; it does not prevent the code
-- from using Source functionalities either
```

We can address the problem using the [phantom constraint pattern](https://www.reddit.com/r/haskell/comments/pnx0ra/effect_is_a_phantom_or_the_redundant_constraint/). Specifically, we can define a "barrier monad transformer" `M` and a phantom typeclass `Eff`:

```haskell
newtype M m a = UnsafeM (m a)
  deriving (Functor, Applicative, Monad)
class Eff (e :: Capability)

deriving instance (MonadIO m, Eff MonadIO) => MonadIO (M m)
deriving instance (HasSink tag a m, Eff (HasSink tag a)) => HasSink tag a (M m)
deriving instance (HasSource tag a m, Eff (HasSource tag a)) => HasSource tag a (M m)
...
```

 such that this won't typecheck:

```haskell
app :: M App SomeType
app = await @"r"
```

instead, one need to introduce an `Eff` constraint:

```haskell
app' :: Eff (HasSource "r" SomeType) => M App SomeType
app' = await @"r"
```

This pattern allows effect management on concrete monads to a great extent and works particularly well with `capability` (it also works `mtl`, `unliftio` and `exceptions`). In microbenchmarks, this kind of usage often performs better than polymorphic code (and never performs worse); I believe that'll also be true in real use. The obvious downside though, is that by using a concrete monad, it invalidates the usage of `Capability.Reflection` and `Capability.Derive`. 

I have already written a small demo library that simplifies the boilerplates away: [[hackage](https://hackage.haskell.org/package/avail-0.1.0.0/candidate), [repo](https://github.com/re-xyr/avail)]. I'd like to know about your thoughts on this pattern (and in particular, the possibility of integrating this into `capability`).

**Comment by aspiwack** [comment]
I've thought about this. And I think that this runs contrary to the spirit of the capability library, which is to make it possible to substitute the monad in a component by some mock implementation for testing.

I'm pretty sure that you can use capability in this style. But I'm not willing to make significant effort to support it. I mean, if you want some thing from this library that will help your style, I'll be happy to provide it. But the advertised style will remain the monad-variable style.

To be honest, though, I don't know what the question or request is in this issue. So let me know if I did answer it, of if you have more in mind.

**Comment by re-xyr** [comment]
Thank you for your answer. I posted this issue just because I wanted feedback on this approach before I publish my library, not as any particular feature request; I'm sorry if this caused confusion.

**Comment by aspiwack** [comment]
No worries. I'm happy to have this conversation.

Thinking about your design some more, if you already have a concrete monad the way you do, I don't know that you need to read this whole thing as an effect system, rather the type classes are capabilities that the concrete monad has. So it can be seen as a more traditional overloading-type situation. I'm not entirely sure what seeing these as effects and requiring them at function call sites by you. But I may be missing something.

**Comment by re-xyr** [comment]
This pattern goes against one aspect of effects: it does not allow pluggable implementations of different effects because it requires a concrete monad for its performance. Nevertheless it preserves another aspect: restricting what a part of program can do in the type level (therefore in compile time). I'm not sure if it is appropriate to actually call this effects or capability, but it is certainly a tool for writing more correct code in some scenarios.
