### ISSUE TITLE
Associate type to tags

### ISSUE THREAD

**Issue by aspiwack** [tweag/capability#65]
Currently, we have to write

```haskell
HasState "mytag" MyType m =>
```

This is all fine for library, and basically necessary for deriving-via combinators. But it's a bit annoying in an application. Where typically, a tag correspond to a given type. _e.g._ `HasReader "config"` would always be followed by the same configuration type. Throughout the entire application. Meh :slightly_frowning_face: .

We should do something about this.

At this point my idea looks a bit as follows. We define a type family

```haskell
type familly TypeOf (s :: Symbol) :: *
```

(with no instance in the library)

And type synonyms like

```haskell
type HasState' s = HasState s (TypeOf a)
```

This way, you could define application-wide tag-to-type associations and have shorthands for them.

Or maybe, in order to avoid the lack of composability that symbol have, we could do

```haskell
type family TypeOf (s :: *) :: *
```

That way they can be defined without orphan instances.

Thoughts?

**Comment by aherrmann** [comment]
Tags are poly-kinded. So, in such cases, we could use the type as a tag as well.

For example:

```
type HasState' s = HasState s s

data Config = ...

foo :: HasState' Config m => m ()
foo = ...
```

**Comment by aspiwack** [comment]
Uh. Please no! Not doing that is sort of the entire point of tags to begin with.
