### ISSUE TITLE
Is `derive` safe?

### ISSUE THREAD

**Issue by re-xyr** [tweag/capability#99]
This is somehow a philosophical question. I believe that the capabilities instances of a monad restricts what user could possibly do within the monad. However `derive` breaks this promise: For a monad, we can now create and use a capability on the fly, all of which is not reflected on the return type.

So, is `derive` “unsafe” in this sense? Should we make it internal and only for use with safer functions like `wrapError`, or add some form of warning to its documentation?

**Comment by aspiwack** [comment]
In the capability library, the restriction is “client side”. That is, when I write a function, I declare which capabilities I require. The monad at which I instantiate my function must provide at least these capabilities.

The `derive` function tells me how to locally provide some capabilities which are not explicitly provided, in terms of those which are provided. That is, you want to read `derive` as “If I can do X, then I know how to do Y”.  I can't quite see how this would be unsafe.

**Comment by re-xyr** [comment]
I think I see the difference. How I viewed this was that the function should not do anything impure except for those specified in the signature; it is the “maximum allowed” set of operations.

**Comment by aspiwack** [comment]
I'm not sure that I understand the conclusion, sorry about that. Are you satisfied with the answers or do you have more questions?

**Comment by re-xyr** [comment]
I think I understand the intention now, thank you for answering.

**Comment by gdeest** [comment]
> I think I see the difference. How I viewed this was that the function should not do anything impure except for those specified in the signature; it is the “maximum allowed” set of operations.

I know you closed the issue, so my answer may not bring any value to this discussion, but I just wanted to point out that `derive` merely expresses how new capabilities can be expressed in terms of ambient capabilities, which already provided by the current monad. New, local capabilities are still interpreted in terms of the old ones ; it does add new fundamental operations (for example, you won't be able to do `IO` if the `MonadIO` is not provided).

**Comment by re-xyr** [comment]
@gdeest Yes, this is a very good explanation. It is basically is what I have realized as I [implemented a very similar function in `availability`](https://github.com/re-xyr/availability/blob/master/src/Availability/Internal/Availability.hs#L131-L144).
